### PR TITLE
Changed ScopeProvider to be specifiable

### PR DESCRIPTION
**Pull request by takahirom**
`○○_mainScopeProvider` is a top-level variable that crashes when touched by another thread. Therefore, if you touch it from a background thread on iOS, it will crash.
On the other hand, I introduced Stately and tried to access the variable when initializing the class.
Please let me know if there is another good way.

### CODE REVIEW

**Comment by micHar** [comment]
What is your use case here? I am not yet sure which elements of Koru should be frozen and which mutable, but I would consider a scope (and therefore scopeProvider) as something that should not be passed from one thread to another.

How does Stately solve the problem?

**Comment by takahirom** [comment]
Thank you, the following crash occurred when I got the SuspendWrapper from the iOS background thread.

```kotlin
public class MyApiNative(
  private val wrapped: MyApi,
) {
  public fun get(): SuspendWrapper<Response> =
      SuspendWrapper(exportedScopeProvider_mainScopeProvider) { // ← crash here
          wrapped.get() 
      }
}
```

Probably because the scope provider is created from another thread at the top level.

`Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread`

However, after making this fix, the iOS simulator stopped working, so I'm investigating the cause.

**Comment by takahirom** [comment]
According to the iOS engineer, the polling process is running in the background thread, and there are other processes as well, so it seems that I want to keep it running in the background due to performance issues. 👀

**Comment by takahirom** [comment]
I wanted to replace ScopeProvider with iOS and put in a ScopeProvider for testing.
Initially, in our product, we created a setter method in the ScopeProvider class.
This policy was good so far, but calling from a thread in the background caused this problem and I had to freeze the ScopeProvider.

The first approach to this problem was to use Stately, which turned out to be pretty bad code. 😅 https://github.com/FutureMind/koru/commit/c59b5db4beb6c99b55b47ade40345e602682988a 
On the other hand, with the current approach(current commit), if you can pass the ScopeProvider when creating XXNative, you can replace the ScopeProvider in the test, so you do not need a setter etc., and you can freeze the ScopeProvider.

**Comment by micHar** [comment]
The idea is to rather create the instances of e.g. MyApiNative on the main thread but perform their work on background. Usually I would create and provide those instances in some kind of dependency injection container on ios (e.g. with Swinject). Then I call suspendwrappers to perform their work on on Dispatcher.Default or just use whatever implicit dispatcher e.g. ktor is using. 

Those wrapper classes can be mutable sometimes so they are not frozen deliberately. I don't think scopes can be frozen either, they are fundamentally mutable afair, e.g. cancel call will probably fail if they are frozen (to be checked though).

You can create as many scope providers as you want, though. And just have one that is created and used solely on bg thread on ios. Or just provide the scope manually to the suspend wrapper - scope providers are just some more codegen magic on top of regular suspendwrappers. 
I don't think it should be necessary, though.

All that being said, I will try to have a longer look and do some tests in the upcoming days.

**Comment by takahirom** [comment]
Thank you. I did a little checking.

> I don't think scopes can be frozen either, they are fundamentally mutable afair, e.g. cancel call will probably fail if they are frozen (to be checked though).

Without freeze
```kotlin
    class MyScopeProvider : ScopeProvider {
        override val scope: CoroutineScope = CoroutineScope(Dispatchers.Default + SupervisorJob())
    }

    @Test
    fun test() {
        runBlocking {
            val myScopeProvider = MyScopeProvider()
//            myScopeProvider.scope.freeze()

            println("beforeLaunch")
            val job = myScopeProvider.scope.launch {
                try {
                    println("startDelay")
                    delay(1000)
                    println("endDelay")
                } catch (e: CancellationException) {
                    println("catch")
                    e.printStackTrace()
                }
            }
            delay(100)
            myScopeProvider.scope.cancel()
            delay(100)
            println("job.isCancelled:"+job.isCancelled)
            println("myScopeProvider.scope.isActive:"+myScopeProvider.scope.isActive)
        }
    }
```

```
beforeLaunch
startDelay
catch
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@415f73f8
Invalid connection: com.apple.coresymbolicationd
job.isCancelled:true
myScopeProvider.scope.isActive:false
```

With freeze (comment in `myScopeProvider.scope.freeze()`)
Probably this is not changed.

```
beforeLaunch
startDelay
catch
kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@61b857c8
Invalid connection: com.apple.coresymbolicationd
job.isCancelled:true
myScopeProvider.scope.isActive:false
```

Since it seems to be common to have CoroutinesScope in an object that freezes, the coroutine object may be considered to be frozen.
If there's anything else you want to know, let me know. 🙏 

> You can create as many scope providers as you want, though. And just have one that is created and used solely on bg thread on ios. Or just provide the scope manually to the suspend wrapper - scope providers are just some more codegen magic on top of regular suspendwrappers.

If you want to do this, I think you need to set Annotation to `@Repeatale` so that you can add more than one.

This PR fix does not affect whether the ScopeProvider needs to be freeze or not, just the change that makes it easier to replace in testing, etc. I think it will not have that much of an impact.

**Comment by takahirom** [comment]
> The idea is to rather create the instances of e.g. MyApiNative on the main thread but perform their work on background. Usually I would create and provide those instances in some kind of dependency injection container on ios (e.g. with Swinject). Then I call suspendwrappers to perform their work on on Dispatcher.Default or just use whatever implicit dispatcher e.g. ktor is using.

There may be a slight misunderstanding.

```kotlin
background {
  val myApi = MyApiNative() // ← this is OK. Because this does not touch scopeProvider
  myApi.getSuspendWrapper() // the problem occur here because touch scopeProvider
}
```

So, I need to distribute each suspend function in DI as follows, but I don't think it is practical. 😭 

```kotlin
val myApi = MyApiNative() 
val suspendWrapper = myApi.getSuspendWrapper() // touch scopeProvider in MainThread

background {
  suspendWrapper.subscribe(...)
}
```

**Comment by takahirom** [comment]
I'm not good at English, so I'm sorry if I've caused you any trouble.

**Comment by micHar** [comment]
Thanks a lot for explaining the problem and writing the tests, this is becoming clearer now :). I still need to consider this and need a few days for that, because I'm in the middle of something.

I hope that doesn't stop you - you probably use a local version of Koru anyway, now. In case you don't, you just need to do your changes and then `publishToMavenLocal` and add `mavenLocal()` to your project dependency repositories.

**Comment by micHar** [comment]
@takahirom I have finally found some time to review it and it's a very good change, it shouldn't have been provided statically directly to the functions anyway. Merged and will publish 0.5.0 shortly, thanks!

**Comment by takahirom** [comment]
Thank you for taking the time to review and writing a document and release! 🙌

**Pull request merged**
