### PR TITLE
do not freeze suspendwrapper and flowwrapper

### PR DESCRIPTION
**Pull request by micHar**

### CODE REVIEW

**Comment by russhwolf** [comment]
Removing these `freeze()` calls will almost certainly cause issues if you cross threads from Swift.

**Comment by micHar** [comment]
The issue was that the wrapped classes sometimes need to be mutable. I had a class that needed to keep a single job at a time - it played a sound - whenever user requested new sound, the previous one has been canceled etc. I froze everything in koru just in case, but I think the FlowWrapper / SuspendWrapper itself doesn't really need to be frozen (which also freezes the wrapped class which caused my issue) - their use case is to **pass data across threads** not to **be passed across thread**. 

I use them to wrap classes which do work on background threads and the immutable data that is passed works fine. Maybe I should add more tests to be sure. E.g. class with function that returns a Flow which operates on Dispatchers.IO. The passed data is still frozen.

Do you have any specific scenario in mind?

**Comment by russhwolf** [comment]
If the wrappers can get touched from multiple threads, I'd expect there to be problems if they're unfrozen. I had some test cases from the original RxSwift article that would switch between threads, and I'm pretty sure they fail without the freezes.
https://github.com/touchlab/SwiftCoroutines/blob/21b68a3fac5f331ff309756532dc2cb1d55fba40/ios/SwiftCoroutinesTests/SwiftCoroutinesTests.swift

(an update to that article is in progress BTW which adjusts some of the scope handling as well as adding Combine and SwiftUI samples. Sample code is in the `combine` branch of tha repo)

**Comment by micHar** [comment]
Thank, I'll look into that. To be honest I still find it a bit difficult to understand how the freezing progresses from one object to another - e.g. somehow the frozen items passed through a flow do not make the flowwrapper frozen, so it's not like "everything it touches".

**Pull request merged**
